# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_resetSystemStats
    rt::HARTNDb_startSystemStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "E:/Vivado_Workspace/e203_2/e203/.Xil/Vivado-23280-MyLaptop/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    rt::set_parameter datapathDensePacking false
    set rt::partid xc7a200tlfbg484-2L
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common.tcl
    set rt::defaultWorkLibName xil_defaultlib

    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog -include {
    {E:/Vivado_Workspace/e203_2/Source Code/rtl/e203/core}
    {E:/Vivado_Workspace/e203_2/Source Code/rtl/e203/perips/apb_i2c}
  } {
      {E:/Vivado_Workspace/e203_2/Source Code/rtl/e203/core/e203_defines.v}
      {E:/Vivado_Workspace/e203_2/e203/e203.srcs/sources_1/imports/sources_1/imports/Floating-Point-ALU-in-Verilog-master/Division/Priority Encoder.v}
      E:/Vivado_Workspace/e203_2/e203/e203.srcs/sources_1/imports/sources_1/imports/Floating-Point-ALU-in-Verilog-master/Division/Addition-Subtraction.v
      E:/Vivado_Workspace/e203_2/e203/e203.srcs/sources_1/imports/sources_1/imports/ALU/Converter.v
      E:/Vivado_Workspace/e203_2/e203/e203.srcs/sources_1/imports/sources_1/new/FALU.v
      E:/Vivado_Workspace/e203_2/e203/e203.srcs/sources_1/imports/sources_1/new/Int_to_Fp.v
      E:/Vivado_Workspace/e203_2/e203/e203.srcs/sources_1/imports/sources_1/imports/Division/IterationQRSqrt.v
      E:/Vivado_Workspace/e203_2/e203/e203.srcs/sources_1/imports/sources_1/imports/Floating-Point-ALU-in-Verilog-master/Multiplication/Multiplication.v
      E:/Vivado_Workspace/e203_2/e203/e203.srcs/sources_1/imports/sources_1/new/QDiv_QSqrt.v
      {E:/Vivado_Workspace/e203_2/Source Code/rtl/e203/perips/apb_adv_timer/adv_timer_apb_if.v}
      {E:/Vivado_Workspace/e203_2/Source Code/rtl/e203/perips/apb_adv_timer/apb_adv_timer.v}
      {E:/Vivado_Workspace/e203_2/Source Code/rtl/e203/perips/apb_gpio/apb_gpio.v}
      {E:/Vivado_Workspace/e203_2/Source Code/rtl/e203/perips/apb_i2c/apb_i2c.v}
      {E:/Vivado_Workspace/e203_2/Source Code/rtl/e203/perips/apb_spi_master/apb_spi_master.v}
      {E:/Vivado_Workspace/e203_2/Source Code/rtl/e203/perips/apb_uart/apb_uart.v}
      {E:/Vivado_Workspace/e203_2/Source Code/rtl/e203/perips/apb_adv_timer/comparator.v}
      {E:/Vivado_Workspace/e203_2/Source Code/rtl/e203/core/e203_biu.v}
      {E:/Vivado_Workspace/e203_2/Source Code/rtl/e203/core/e203_clk_ctrl.v}
      {E:/Vivado_Workspace/e203_2/Source Code/rtl/e203/core/e203_clkgate.v}
      {E:/Vivado_Workspace/e203_2/Source Code/rtl/e203/core/e203_core.v}
      {E:/Vivado_Workspace/e203_2/Source Code/rtl/e203/core/e203_cpu.v}
      {E:/Vivado_Workspace/e203_2/Source Code/rtl/e203/core/e203_cpu_top.v}
      {E:/Vivado_Workspace/e203_2/Source Code/rtl/e203/core/e203_dtcm_ctrl.v}
      {E:/Vivado_Workspace/e203_2/Source Code/rtl/e203/core/e203_dtcm_ram.v}
      {E:/Vivado_Workspace/e203_2/Source Code/rtl/e203/core/e203_exu.v}
      {E:/Vivado_Workspace/e203_2/Source Code/rtl/e203/core/e203_exu_alu.v}
      {E:/Vivado_Workspace/e203_2/Source Code/rtl/e203/core/e203_exu_alu_bjp.v}
      {E:/Vivado_Workspace/e203_2/Source Code/rtl/e203/core/e203_exu_alu_csrctrl.v}
      {E:/Vivado_Workspace/e203_2/Source Code/rtl/e203/core/e203_exu_alu_dpath.v}
      {E:/Vivado_Workspace/e203_2/Source Code/rtl/e203/core/e203_exu_alu_fpuctrl.v}
      {E:/Vivado_Workspace/e203_2/Source Code/rtl/e203/core/e203_exu_alu_lsuagu.v}
      {E:/Vivado_Workspace/e203_2/Source Code/rtl/e203/core/e203_exu_alu_muldiv.v}
      {E:/Vivado_Workspace/e203_2/Source Code/rtl/e203/core/e203_exu_alu_rglr.v}
      {E:/Vivado_Workspace/e203_2/Source Code/rtl/e203/core/e203_exu_branchslv.v}
      {E:/Vivado_Workspace/e203_2/Source Code/rtl/e203/core/e203_exu_commit.v}
      {E:/Vivado_Workspace/e203_2/Source Code/rtl/e203/core/e203_exu_csr.v}
      {E:/Vivado_Workspace/e203_2/Source Code/rtl/e203/core/e203_exu_decode.v}
      {E:/Vivado_Workspace/e203_2/Source Code/rtl/e203/core/e203_exu_disp.v}
      {E:/Vivado_Workspace/e203_2/Source Code/rtl/e203/core/e203_exu_excp.v}
      {E:/Vivado_Workspace/e203_2/Source Code/rtl/e203/core/e203_exu_fpu.v}
      {E:/Vivado_Workspace/e203_2/Source Code/rtl/e203/core/e203_exu_fregfile.v}
      {E:/Vivado_Workspace/e203_2/Source Code/rtl/e203/core/e203_exu_longpwbck.v}
      {E:/Vivado_Workspace/e203_2/Source Code/rtl/e203/core/e203_exu_nice.v}
      {E:/Vivado_Workspace/e203_2/Source Code/rtl/e203/core/e203_exu_oitf.v}
      {E:/Vivado_Workspace/e203_2/Source Code/rtl/e203/core/e203_exu_regfile.v}
      {E:/Vivado_Workspace/e203_2/Source Code/rtl/e203/core/e203_exu_wbck.v}
      {E:/Vivado_Workspace/e203_2/Source Code/rtl/e203/core/e203_ifu.v}
      {E:/Vivado_Workspace/e203_2/Source Code/rtl/e203/core/e203_ifu_ifetch.v}
      {E:/Vivado_Workspace/e203_2/Source Code/rtl/e203/core/e203_ifu_ift2icb.v}
      {E:/Vivado_Workspace/e203_2/Source Code/rtl/e203/core/e203_ifu_litebpu.v}
      {E:/Vivado_Workspace/e203_2/Source Code/rtl/e203/core/e203_ifu_minidec.v}
      {E:/Vivado_Workspace/e203_2/Source Code/rtl/e203/core/e203_irq_sync.v}
      {E:/Vivado_Workspace/e203_2/Source Code/rtl/e203/core/e203_itcm_ctrl.v}
      {E:/Vivado_Workspace/e203_2/Source Code/rtl/e203/core/e203_itcm_ram.v}
      {E:/Vivado_Workspace/e203_2/Source Code/rtl/e203/core/e203_lsu.v}
      {E:/Vivado_Workspace/e203_2/Source Code/rtl/e203/core/e203_lsu_ctrl.v}
      {E:/Vivado_Workspace/e203_2/Source Code/rtl/e203/core/e203_reset_ctrl.v}
      {E:/Vivado_Workspace/e203_2/Source Code/rtl/e203/core/e203_srams.v}
      {E:/Vivado_Workspace/e203_2/Source Code/rtl/e203/subsys/e203_subsys_clint.v}
      {E:/Vivado_Workspace/e203_2/Source Code/rtl/e203/subsys/e203_subsys_gfcm.v}
      {E:/Vivado_Workspace/e203_2/Source Code/rtl/e203/subsys/e203_subsys_hclkgen.v}
      {E:/Vivado_Workspace/e203_2/Source Code/rtl/e203/subsys/e203_subsys_hclkgen_rstsync.v}
      {E:/Vivado_Workspace/e203_2/Source Code/rtl/e203/subsys/e203_subsys_main.v}
      {E:/Vivado_Workspace/e203_2/Source Code/rtl/e203/subsys/e203_subsys_mems.v}
      {E:/Vivado_Workspace/e203_2/Source Code/rtl/e203/subsys/e203_subsys_nice_core.v}
      {E:/Vivado_Workspace/e203_2/Source Code/rtl/e203/subsys/e203_subsys_perips.v}
      {E:/Vivado_Workspace/e203_2/Source Code/rtl/e203/subsys/e203_subsys_plic.v}
      {E:/Vivado_Workspace/e203_2/Source Code/rtl/e203/subsys/e203_subsys_pll.v}
      {E:/Vivado_Workspace/e203_2/Source Code/rtl/e203/subsys/e203_subsys_pllclkdiv.v}
      {E:/Vivado_Workspace/e203_2/Source Code/rtl/e203/subsys/e203_subsys_top.v}
      {E:/Vivado_Workspace/e203_2/Source Code/rtl/e203/perips/apb_i2c/i2c_master_bit_ctrl.v}
      {E:/Vivado_Workspace/e203_2/Source Code/rtl/e203/perips/apb_i2c/i2c_master_byte_ctrl.v}
      {E:/Vivado_Workspace/e203_2/Source Code/rtl/e203/perips/apb_adv_timer/input_stage.v}
      {E:/Vivado_Workspace/e203_2/Source Code/rtl/e203/perips/apb_uart/io_generic_fifo.v}
      {E:/Vivado_Workspace/e203_2/Source Code/rtl/e203/perips/apb_adv_timer/prescaler.v}
      {E:/Vivado_Workspace/e203_2/Source Code/rtl/e203/general/sirv_1cyc_sram_ctrl.v}
      {E:/Vivado_Workspace/e203_2/Source Code/rtl/e203/perips/sirv_AsyncResetReg.v}
      {E:/Vivado_Workspace/e203_2/Source Code/rtl/e203/perips/sirv_AsyncResetRegVec.v}
      {E:/Vivado_Workspace/e203_2/Source Code/rtl/e203/perips/sirv_AsyncResetRegVec_1.v}
      {E:/Vivado_Workspace/e203_2/Source Code/rtl/e203/perips/sirv_AsyncResetRegVec_129.v}
      {E:/Vivado_Workspace/e203_2/Source Code/rtl/e203/perips/sirv_AsyncResetRegVec_36.v}
      {E:/Vivado_Workspace/e203_2/Source Code/rtl/e203/perips/sirv_DeglitchShiftRegister.v}
      {E:/Vivado_Workspace/e203_2/Source Code/rtl/e203/perips/sirv_LevelGateway.v}
      {E:/Vivado_Workspace/e203_2/Source Code/rtl/e203/perips/sirv_ResetCatchAndSync.v}
      {E:/Vivado_Workspace/e203_2/Source Code/rtl/e203/perips/sirv_ResetCatchAndSync_2.v}
      {E:/Vivado_Workspace/e203_2/Source Code/rtl/e203/perips/sirv_aon.v}
      {E:/Vivado_Workspace/e203_2/Source Code/rtl/e203/perips/sirv_aon_lclkgen_regs.v}
      {E:/Vivado_Workspace/e203_2/Source Code/rtl/e203/perips/sirv_aon_porrst.v}
      {E:/Vivado_Workspace/e203_2/Source Code/rtl/e203/perips/sirv_aon_top.v}
      {E:/Vivado_Workspace/e203_2/Source Code/rtl/e203/perips/sirv_aon_wrapper.v}
      {E:/Vivado_Workspace/e203_2/Source Code/rtl/e203/perips/sirv_clint.v}
      {E:/Vivado_Workspace/e203_2/Source Code/rtl/e203/perips/sirv_clint_top.v}
      {E:/Vivado_Workspace/e203_2/Source Code/rtl/e203/debug/sirv_debug_csr.v}
      {E:/Vivado_Workspace/e203_2/Source Code/rtl/e203/debug/sirv_debug_module.v}
      {E:/Vivado_Workspace/e203_2/Source Code/rtl/e203/debug/sirv_debug_ram.v}
      {E:/Vivado_Workspace/e203_2/Source Code/rtl/e203/debug/sirv_debug_rom.v}
      {E:/Vivado_Workspace/e203_2/Source Code/rtl/e203/perips/sirv_expl_axi_slv.v}
      {E:/Vivado_Workspace/e203_2/Source Code/rtl/e203/perips/sirv_flash_qspi.v}
      {E:/Vivado_Workspace/e203_2/Source Code/rtl/e203/perips/sirv_flash_qspi_top.v}
      {E:/Vivado_Workspace/e203_2/Source Code/rtl/e203/general/sirv_gnrl_bufs.v}
      {E:/Vivado_Workspace/e203_2/Source Code/rtl/e203/general/sirv_gnrl_dffs.v}
      {E:/Vivado_Workspace/e203_2/Source Code/rtl/e203/general/sirv_gnrl_icbs.v}
      {E:/Vivado_Workspace/e203_2/Source Code/rtl/e203/general/sirv_gnrl_ram.v}
      {E:/Vivado_Workspace/e203_2/Source Code/rtl/e203/perips/sirv_hclkgen_regs.v}
      {E:/Vivado_Workspace/e203_2/Source Code/rtl/e203/fab/sirv_icb1to16_bus.v}
      {E:/Vivado_Workspace/e203_2/Source Code/rtl/e203/fab/sirv_icb1to2_bus.v}
      {E:/Vivado_Workspace/e203_2/Source Code/rtl/e203/fab/sirv_icb1to8_bus.v}
      {E:/Vivado_Workspace/e203_2/Source Code/rtl/e203/debug/sirv_jtag_dtm.v}
      {E:/Vivado_Workspace/e203_2/Source Code/rtl/e203/perips/sirv_jtaggpioport.v}
      {E:/Vivado_Workspace/e203_2/Source Code/rtl/e203/mems/sirv_mrom.v}
      {E:/Vivado_Workspace/e203_2/Source Code/rtl/e203/mems/sirv_mrom_top.v}
      {E:/Vivado_Workspace/e203_2/Source Code/rtl/e203/perips/sirv_plic_man.v}
      {E:/Vivado_Workspace/e203_2/Source Code/rtl/e203/perips/sirv_plic_top.v}
      {E:/Vivado_Workspace/e203_2/Source Code/rtl/e203/perips/sirv_pmu.v}
      {E:/Vivado_Workspace/e203_2/Source Code/rtl/e203/perips/sirv_pmu_core.v}
      {E:/Vivado_Workspace/e203_2/Source Code/rtl/e203/perips/sirv_qspi_arbiter.v}
      {E:/Vivado_Workspace/e203_2/Source Code/rtl/e203/perips/sirv_qspi_fifo.v}
      {E:/Vivado_Workspace/e203_2/Source Code/rtl/e203/perips/sirv_qspi_media.v}
      {E:/Vivado_Workspace/e203_2/Source Code/rtl/e203/perips/sirv_qspi_physical.v}
      {E:/Vivado_Workspace/e203_2/Source Code/rtl/e203/perips/sirv_queue.v}
      {E:/Vivado_Workspace/e203_2/Source Code/rtl/e203/perips/sirv_queue_1.v}
      {E:/Vivado_Workspace/e203_2/Source Code/rtl/e203/perips/sirv_repeater_6.v}
      {E:/Vivado_Workspace/e203_2/Source Code/rtl/e203/perips/sirv_rtc.v}
      {E:/Vivado_Workspace/e203_2/Source Code/rtl/e203/general/sirv_sim_ram.v}
      {E:/Vivado_Workspace/e203_2/Source Code/rtl/e203/perips/sirv_spi_flashmap.v}
      {E:/Vivado_Workspace/e203_2/Source Code/rtl/e203/general/sirv_sram_icb_ctrl.v}
      {E:/Vivado_Workspace/e203_2/Source Code/rtl/e203/perips/sirv_tl_repeater_5.v}
      {E:/Vivado_Workspace/e203_2/Source Code/rtl/e203/perips/sirv_tlfragmenter_qspi_1.v}
      {E:/Vivado_Workspace/e203_2/Source Code/rtl/e203/perips/sirv_tlwidthwidget_qspi.v}
      {E:/Vivado_Workspace/e203_2/Source Code/rtl/e203/perips/sirv_wdog.v}
      {E:/Vivado_Workspace/e203_2/Source Code/rtl/e203/perips/apb_spi_master/spi_master_apb_if.v}
      {E:/Vivado_Workspace/e203_2/Source Code/rtl/e203/perips/apb_spi_master/spi_master_clkgen.v}
      {E:/Vivado_Workspace/e203_2/Source Code/rtl/e203/perips/apb_spi_master/spi_master_controller.v}
      {E:/Vivado_Workspace/e203_2/Source Code/rtl/e203/perips/apb_spi_master/spi_master_fifo.v}
      {E:/Vivado_Workspace/e203_2/Source Code/rtl/e203/perips/apb_spi_master/spi_master_rx.v}
      {E:/Vivado_Workspace/e203_2/Source Code/rtl/e203/perips/apb_spi_master/spi_master_tx.v}
      {E:/Vivado_Workspace/e203_2/Source Code/rtl/e203/perips/apb_adv_timer/timer_cntrl.v}
      {E:/Vivado_Workspace/e203_2/Source Code/rtl/e203/perips/apb_adv_timer/timer_module.v}
      {E:/Vivado_Workspace/e203_2/Source Code/rtl/e203/perips/apb_uart/uart_interrupt.v}
      {E:/Vivado_Workspace/e203_2/Source Code/rtl/e203/perips/apb_uart/uart_rx.v}
      {E:/Vivado_Workspace/e203_2/Source Code/rtl/e203/perips/apb_uart/uart_tx.v}
      {E:/Vivado_Workspace/e203_2/Source Code/rtl/e203/perips/apb_adv_timer/up_down_counter.v}
      {E:/Vivado_Workspace/e203_2/Source Code/rtl/e203/soc/e203_soc_top.v}
    }
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top e203_soc_top
    rt::set_parameter enableIncremental true
    rt::set_parameter markDebugPreservationLevel "enable"
    set rt::reportTiming false
    rt::set_parameter elaborateOnly true
    rt::set_parameter elaborateRtl true
    rt::set_parameter eliminateRedundantBitOperator false
    rt::set_parameter dataflowBusHighlighting false
    rt::set_parameter generateDataflowBusNetlist false
    rt::set_parameter dataFlowViewInElab false
    rt::set_parameter busViewFixBrokenConnections false
    rt::set_parameter elaborateRtlOnlyFlow true
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
    rt::set_parameter srlDepthThreshold 3
    rt::set_parameter rstSrlDepthThreshold 4
# MODE: 
    rt::set_parameter webTalkPath {}
    rt::set_parameter synthDebugLog false
    rt::set_parameter printModuleName false
    rt::set_parameter enableSplitFlowPath "E:/Vivado_Workspace/e203_2/e203/.Xil/Vivado-23280-MyLaptop/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_rtlelab -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
